---
apiVersion: v1
kind: Namespace
metadata:
  name: dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: shapai/myapp:<TAG>
        imagePullPolicy: Always
        name: myapp

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp
  namespace: dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000  # Assuming your app listens on port 5000
  selector:
    app: myweb
  type: ClusterIP
